class Board {
    static board = [
            [ Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall , Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall , Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall , Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall , Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall ,  Element.Wall,  Element.Wall,  Element.Wall, Element.Board, Element.Board,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board,  Element.Wall,  Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall,  Element.Wall, Element.Board,  Element.Wall],
            [ Element.Wall, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board, Element.Board,  Element.Wall],
            [ Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall,  Element.Wall],
          ];

    static addFood(numberOfFood) {
        let numberOfEmptyFields = 0;
        for (let y = 0; y < 28; y++) {
            for (let x = 0; x < 50; x++) {
                if (!board[y][x]) {
                    numberOfEmptyFields++;
                }
            }
        }
        
        for (let i = 0; i < numberOfFood; i++) {
            let numberOfFieldToAssFood = Math.random() * numberOfEmptyFields + 1 - i
            let yOfFoodField = 0
            let xOfFoodField = 0
            for (let y = 0; y < 28; y++) {
                for (let x = 0; x < 50; x++) {
                    if (!board[y][x] && numberOfFieldToAssFood > 0) {
                        yOfFoodField = y
                        xOfFoodField = x
                        numberOfFieldToAssFood--;
                    }
                }
            }
    
            board[yOfFoodField][xOfFoodField] = Element.Food
        }
        
    }
    
}